hash-format = "sha256"

[[files]]
file = "mods/accessories-cc-layer.pw.toml"
hash = "1373a10883b4904820a46fc4e76defb0ebd05e199647d56029fa1d62eb5fc1cb"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "7ca5e73db0b8cc37d077f774b22cf3727b15ba8fbcfc988698e6d5db898b7d80"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "06c9c68e1cd0b3f4964301d10256ea45788490cb839251d8191a5bafd65c3e18"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "f1c6e7bcc55913a2b8a5a37615af075e054bf4528ea90af7a137c672ce69e088"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "8fc2033ee6c4f2ca22b54c3c3e3e31e7fb16c67a24ea55740a1a4e4d9e9b856c"
metafile = true

[[files]]
file = "mods/backported-wolves.pw.toml"
hash = "457738950994dc1cd4d3e3a572b739db95b49c3558114020dc129a678b87b733"
metafile = true

[[files]]
file = "mods/bartering-station.pw.toml"
hash = "77d4c90bf80df19ce5329a95f9be63c9340ac0304dee59d8b9aedaf7ac25d1cc"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "23c6c221ffaed6fc19bf505f6d821722c630a8e549d7548d252bbd545eb979fa"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "90a61faac19eb88a2dbb4b201e1e99633c193da142c89fb6ae97b3b1d2901f99"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7414b8b144fa39ca7bf0b9a422adde055d4c6583e6a29f14b92dfcfe08f2e995"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "a94f72f43138c445f653cda7e7b53d082d8fb8d66bdd0de8ba1a291838f43d90"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "4d5ba0ec7ea7abf0ef76f3f08853bd7c886eec95b1795cbeacaba8bc608e2913"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "96c84fb1d60d877ff659d0ed67b79ab3dbf5a2e7fc78daf2d654cfe36b845831"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "853df4ab2418f347cbb1e3b4ca6c82b2a517a8e4e8ccabcd42c27e3496707a32"
metafile = true

[[files]]
file = "mods/create-additional-logistics.pw.toml"
hash = "0e6247a0e0465364d3ae614e43fc66ab5351613ec86c8d9202c0886f58361d42"
metafile = true

[[files]]
file = "mods/create-cafe.pw.toml"
hash = "c01e6f68aeec0f8ac8299d2fac9a624075dd759e9ccf7c011729c24019422f92"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "263d284bf1c24f54858437079ef4e32c5f077caff23b455a6ca43eb662b2aa1b"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "aa8711ff3f1d590b8c3e4e092927e5a697d585e21c52107ddc559c93ffebdaed"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "b4bfb924f7f9bbc597881cd190ce620613147fea154e694ed16c0248d64f60cf"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "2bd95f6e436131ce408bd7b84f42b2bc265c8aea70be8b516bb5c27834e7a255"
metafile = true

[[files]]
file = "mods/create-high-pressure.pw.toml"
hash = "e259afa9aa04240c68a0beeb78ed139d6b4491a5dd3a113db4208ddd55cda1d1"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "d1218830d3170e3d4753752713dc39d3ff38b802556c90e669669390bc7ded39"
metafile = true

[[files]]
file = "mods/create-numismatics-crafting.pw.toml"
hash = "d894dcde571ebeb14b2d693eb283f9c2bdec8080b9bd5422e7fa3e8bfe59e12c"
metafile = true

[[files]]
file = "mods/create-security-program.pw.toml"
hash = "c23ef0369eebbb799cd53cbb9c79b2ffdd314a9636ac287f3cc614a92774730a"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "79b2822a18c083932eefa1288a235e22259838e345f3b84da721df6ff1bbba6f"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1383490f768c8bcf9f396f6f1e4cfcf031415c032d4e637c08b9f15c34fb6415"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9d0ae906a415daafac578469bdcb6680a1336d0deaef7fb112a85c99c78a045a"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "e3037ad0f9c75f94f56feb0f155575c79e79b56e750b9d29b591e25c82f72d08"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "2a4b74ea27272adaaafa957798cb443ccd7e807ef3b12e1cc737255046af0e5d"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "6da4cfa8aa1aa4846c2f4795fd470337326b5c4d36814f2ca50a7238c290cc8c"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "5991b8224cb2d276910f45f678f4c154eded767924c8f97a7647b397d34d649f"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3d7f1c1179fed2e0a0e1906f86d3d225318df98905c50dbad7bc2e8edced870c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f908135463f02a4262916e0e277c1808b86f3b287e0335580967f89de650a5bf"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d4107853438a5bb3c7adae5e0d5cadca6823858a560ab1156be09592676a6264"
metafile = true

[[files]]
file = "mods/farmers-delight-compat.pw.toml"
hash = "fa6b688cae082d95e258316efebc621a00b850878b08bbeb630fb3ea02908e67"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "4cc9553998df37ece6c707d960da5ee47dc76929050bb06b4d9f876d6fbf8a4c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "b2c9813c936a2ee8a4ef1d54e761889aa425befec99448df8fd91f5518e3d9ad"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "fdf3773509e1be300d1e314b4c975ef7da81e7fb6f0bea7e8cbf1c147960f918"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "376f8a190f00bd120193d7a665ebe1b03dfe329cc395f7d944f7216c1182c84d"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "952e8743d8452d98c491a2e71bffbba3e89fb26369211c15c84fad89b6e17fea"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "252677223ba5ee1dbcbff6c6df291ddef021e967de627837e75e41355241f440"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "e49c0bc4bd5d3b12d1b26d2fb462753f59b068bdcdeff549496b8ad0fb9f225f"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "7ca55cd661721ca944979439aac5160009e07ce2568fbf8aee53e019f3e55fba"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "79c990b977cff2edcd25258c91a04feae5ce3cbc619f2b9e5af0861f83024791"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "d3a43ccc58ff4f8260d99081ef5c20200650c274cf2b8970d75b794a14767502"
metafile = true

[[files]]
file = "mods/mcef.pw.toml"
hash = "e54c6dc1b57c90006e8240f45998953f28ae53769c4c2682b7f341f75f1a0b52"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "cb101c29fc90fb63abf3c06cf8f49caed8dd358814a21cef9e35e99484856128"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "da4f04ae30c0b60d8ce5cdc2800c7634f171b549c32cb99b8dc33e155a3f9c87"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "186909f73870979511db893fca2e2a318b311361f168d425ba0e58fc539188ee"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "8dd17f19e28b517c1ce56a2024ece8a37ca9bc866079d23969cc3811577861a4"
metafile = true

[[files]]
file = "mods/multibeds.pw.toml"
hash = "4eccf9af8df16710a00e198c7997a948e6ed3ecccd40d5aee8e6f7ffbf6dcd01"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "92c2a6ff1bf3741ee631bf737544121198c3e685726d7eb04bd6b47e3e1a0da5"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "0409efadeef015a2331948d4a219cd1bbbe827579ea4e3ce7c5df1e09f55a808"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "1a1b5ebfca9831e395d4c39b289ecb9b6100ce28dce11d0de104d6e25d5029f3"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "2dc838532525d7cc655d650584e48f19c76ace8f0df1e977643efef9f78f7929"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "ff8200ec4dd6ca681e1d290774bc136fd00ab2d2ecc9b4d518ddafaf1445753d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9c77eb8ae03c4e64cbddc73687c71a9270c1d90bf61cf057e59753c5a52a7804"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "c00da0fbe9d525e8efc50c8ddecf9f7bbfe34a5050c1a0ab0b417986d9a44149"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "1f0d49cdf1c13f18d0318d95ce721d2e1d4c9c42379fdf90840b53f76e19770c"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "e71c242164a1fdbe43286bbf9a6562859becb2b32378a68ab1768238790b9063"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "0724256dddc5ed2a09b7a48e97526e88288b7b79c0d3edd7504c84f896f4fe9e"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "2bcee75d08b33dd6506b7cd3f67ea9d0d2c1bf14e26728fa8e12ef19c895b165"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "61ce39e0388790c8ac54c67882adae2fc769b1c624fb768d935c0e8d8c90f2e0"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "13585b49c3377716494f7a65bf5031cfe66a5059bdba0eafe6ad4158df6cb7de"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "4875a4be99e7ddba1daa1ef72e29419c40d26feafe0ba995084067e040d97151"
metafile = true

[[files]]
file = "mods/saros-road-blocks.pw.toml"
hash = "12897dddf9d51d8d8db00bb9e524b62cfa91fe2e20314a1ffb3bf1957890319d"
metafile = true

[[files]]
file = "mods/saros-road-signs.pw.toml"
hash = "9c31c319f628b69bdab6cbb51fa2afdca8d9740d0b7a0b8cc126b33bf9d65afd"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "115ab3c890dd7d9441a6290e56f658926681038cf4e7b863542c20213b23ee20"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "acd25c6c1c5baf9587e7f32e71d799167e7024fa5dbc34c8d9cfb404b69f8f4b"
metafile = true

[[files]]
file = "mods/shetiphiancore.pw.toml"
hash = "d151985b640509c0d44c26b0a35ac827dba9764725c83f41629a04845d1607a8"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "f49c7302f7a044aae67740fac3a7558ca2f26b3a89a69a3940d516a40e3b75b7"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "1c696a4ad7f0cd380aeb3750dd0c704a843868abb716418a5b619eb66a476c43"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "69d43912cbe5b2d6c48c0f39bf53989bd49e16608e4eaa4866500f02230649b3"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "aef3c0c9ec9738af9682b335a5c732b7b885299821f3ab4ae010a216171ef43a"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "aa9df88ba53e48af7ad9958652007be80873ea305f4f72ae30bb4fbb2a0de2a4"
metafile = true

[[files]]
file = "mods/ultimate-car-mod.pw.toml"
hash = "dcf38149b4ee0ff130c30e61b30df0fc4ef77147a8e8010b9a2de39dd32c048c"
metafile = true

[[files]]
file = "mods/vinurl.pw.toml"
hash = "2cf9b93b639638b920d94a307c698bbb3678f6e9c39993415057ede7860465e8"
metafile = true

[[files]]
file = "mods/vminus.pw.toml"
hash = "44ce2f2d7352101dd40761bd46b5f3db296a4c02edb0f7ccc97e94b3861765ee"
metafile = true

[[files]]
file = "mods/webdisplays.pw.toml"
hash = "f4a8f0240c98bb800bac018fb85340f781600ec911286b78245aa83cce060246"
metafile = true

[[files]]
file = "mods/wojanek!.pw.toml"
hash = "422cfc86289a30dc52c41693658d63745ab8191996d775da568fc4bb541154d9"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "bd1dc13316e2aa9b56c89e7e974057f8da8d6bbfe707ba4210109fc612b782e3"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "7e6cb03a09f0d277a5725bfc7570c225c24d8924d4ea97fab6395b2a46127b32"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e0068a15a3aaa5ea65db725e9a060dc5aaf237f401f5eed219e4457aa8f24b20"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "a64bea133c7b08a886e1eecc7195c72ec2fd3429293519c954928deb201baffe"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "6607dc96744a196e806724ec3809feed06f3b423523ebe84c6862c23f2a60bfc"
metafile = true
