hash-format = "sha512"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "91e517e02a38e423af0bf2f49e22f5069e2775317c8d20ef62d7aa557d15df62"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "82b2d231099a20916315cf11085ec4aa4d9e029bad67c20c017b7f9ae48dabb5"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b3d7d14219e2cef10c909566f9cf67b8df29f7a9b5ecb5dd925ac0d27a42747d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "de069b5f13a25ffc02589f00aaf2cc439ad7df02cdae999916e73bf077998f43"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/autoreconnect.pw.toml"
hash = "c6f16688cf57d7bf77e10d746cb4ee9d07b4d5b6c68a08ff74680f5685e30eac"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/backported-wolves.pw.toml"
hash = "d3518d8d4e53cd1d0f1942aacbdf43a0a0daa84bea3b4d7c9533bbbab08c555f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/bartering-station.pw.toml"
hash = "4fcb31ac78be6c2482237814cd13af31f08d6ab5bcc1f1e151680edd999a5d6a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "e5ef518e3c19846d8ca704be965d12e397fc56e1fc0eb58508597de1dcba7d24"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "8f828f9d99d72c70d05395f82da985fdeaaf5182d2f8486176627d89d8c6ddc3"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "8bbd8d18f0ef2a82be6ac780abf4bc838a0bde5abbc7a092e0c9ffed0c1ba212"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "aa691b0c5ac0848ac32f86ae7e451bb8223f27920ba4475419e359eeb2ca3b6c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "7221028772dcefdf6e61c9994688eaeb4fe3efbf05a50df5db67994a6fc6dee1"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "c3cfe5ed514c71830e64d0ecc2fa4fd121f86776bdf172e56b462b95b8cfce27"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "0ee40b31741383f34b630cf533b47b1cae06d5187e4aa156c81b2ef1940e8101"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-additional-logistics.pw.toml"
hash = "e6df0e058af6d2b072d5b4c19bdaf3cc6d5aa8ec9ddff352e1624ffc5eb6ba7f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "75d165cf0befe2d797f46d00c56ab2644d658468316b526328c31ae3d86feabf"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "7a460c9be54ea8245e8a965a14fed79cd3e2aa977fc79ae20bf0c5c5c20213a2"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "4064acab8132585a4c21a3fef6bfb9bb598d4ae9b3a6c4adc4d1e90dd361eaf6"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "f7fd9ff7b8c368ab014f69528842598bb558d5e29b8c647a9d7594f1fa805824"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "da6ac85defc85348a637ffc6492a83c2d5f30368804af8f544ecd719e20db7e2"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-high-pressure.pw.toml"
hash = "59ac132dc9a9bba574e3ba318d064d953bad9682efe08d8aae28a2f5976640ab"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "76ca3b317ee6c9dbb617958f676646957b66a0944a35bfc50048435b344469dc"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-security-program.pw.toml"
hash = "24e0b22061865819cd627bf1c23fdebc383c341c04138b40602b4e8199791483"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "00dfaee1427d081f75fe733492f305285360cece410766a0a30cfaba5e73a84f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "7e48d71c2a18e5bbc68512b1856da8b3abd4052163287cbbe42fdc71984dc57a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "35a2ab98baed86d844d909400f8ab47bf3829530f8f7b037ce086a19bd268cbd"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "ac3fc93c73a20f8bfa8adb077ba603d549e5e1a62c32916abc48b433203ce47a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/devices-mod.pw.toml"
hash = "8fcebf14e271cf5994195d5621533800da071496367071345b20f6a10c2df43f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0b04ed099c2e3fef0a838498900edb04f93156a6425018fbdd411bd9d9996a6b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "7a59f84f4911b54a694ed1f922334b6ce529d088ecec9efbd9dfbcdfaa73c19a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "9579c0d48cb39809310911564165215e8a467df9b2b95d819c6a8d493fbc9fef"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "3cdf625ca8105dcc8407cdd63067575319f455ded91beaacbd6ed9fd580df657"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9151984e5e12edad40bfadcdcc75bb932c74a7a6d9a7116f17cdb293f5dae245"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "fa4efa6ad10f58813530a319b3b227b8dabfcd312c2c9250ccc4ce5de0bd02dc"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6a2b9c8cd9e719c049713bab363b6b21dcc00504b596653545b06a663319700d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/eyemod-phone.pw.toml"
hash = "2344318f4a96959bb855692cb544539a886cb6c720a66301b84fad40c472fe09"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "012f99eec20982fe7bd67ded0d79d55e82991f3165dfa94fa66f38dd9d010f77"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/farmers-delight-compat.pw.toml"
hash = "b6f9ed5617397916703b94bd70923a10f9bf9be2dd9ad9fd9d3c5aee8b68d46a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "159c6ff75cd71e216404cf2ec3270666bf0f0318ecaf388b6b498aa6adf64672"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "bf24a150584577da1674f7b9179bafbfcf1ee77f4687e59e133a5dba0a5aa6dc"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "faa8443fb4238730fc6314e0d8d0722ed5b50b76c3cd5b08063184c2af7b14fe"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "c442358994c36d3dc41761c52c96afa145333afd0d63d7cc4c8bff8c77d56601"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "63ad986805033490bdb263a0d6e67691b84dad9fbbe1244c63aaa5af9b71d81a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "db5c0ef4a3fe63a6c3d62af16260626bb166e77fa8ee8eb51ef8aa36e1cd12a7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eb9782953c41732e9f707c7386c70f6c0bfb9191cef4707a1ad157597ef08620"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "c92426c22e55acc223f14ab21d2819ce3bfdfefb256d9c4a335b48603ca59a65"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "a1f301d081d26d347a6d340a614ee0593822080d774d9834a37676ca56dddf90"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6fc87bf5b5dabcbe76b61e7b8432981fd9550e554c71fd24727e2888e180b017"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "3cbaaaa3db6ec109a4a36a12f1ad2f34bc8f630b4764671794ba0c687326950c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "1c3dce9ce6100ae67aa74b458e1ca7f0303af01f2c79a8e7b58cb219b9e78b09"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "475ad21571736259fed4aea299e1774348f340e70db37018fff491824f133f4f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "f71c41434fd45053c6878069875611f3bed05c69512efe55546d75df548df2a0"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "746b646935eb19c80ff30c9348ed159ac656e5963cc9209929e85cc75db95b1d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "5d92d7f97b32883be4b27d42a2517036437369a5fc82399e6fc2cc825e387061"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "06aa4e87f6c1c81f9961718f277d7d4acb74a181b16780a8ba329460349143ae"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "b6ee3ec9dbddfc3601ffe164c72e1b55d900b467283c709ce1a131112771ab6a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/multibeds.pw.toml"
hash = "ed66f4c75a4492a19c3c012dfd491decddb1267695152efe0099969e58a3b209"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d2afceec5a35a1f27d2990301be13a2131498b5643ce4e5faa03b3fbad765b1e"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "cb88d2d0669450c6b85af0d12d2471496c0262bf1339b8b26f428ba1e5790bae"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "0fb401d1aacd9572cc68d3c0120bc4a116c987811287128e7414819fcae766e1"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "a8420097850d9df5ff1c274ca24bd3ef6f1ab5e8d4c10a201cd00b4d2305de78"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "daeed96e65e87e5c54621237a810f9cd49b0930c7ee116be218dffef0152f00f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "0174a904b36636af3775b483c5cab4faa87f154b1505af02da2187b4be7a817e"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "f11dd16ab22c35236fd8b9c549486f142d0794715dac7027dc691302d0146391"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "365ca360106defbd6fa8441e3a4b5405a6885c57c995a7c48be6ce7d989bbf5d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "b81f04fb3ef57706e9cc303dc33c83e430f676f8b7e00f7a58c87f4f7b2b1959"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "8068be47e1f465b38532961d9e53ee1cf11a32a5331e6ba0c41ac84149ccf2c4"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/realms-button-remover.pw.toml"
hash = "304eaa8f1e229e2b67132d1a182da782a7611ff638dc556fd7a685ecd2c78369"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "bfcbb710922c91bda1c29b39951968aeafdcf1a359881d1f3203d1008c6caf35"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "391922c84079f3ae61c798020230f2117f3a52034ea815defc842bed0d3d3186"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "b1fd99e023b9261832c0a22391483eeee493f795fdbe6b72e17a225a5184d097"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "1ed2a62222ce2cfbc66ca5de8e3fdde1a64315aba04b1c21ce4e4229917679dd"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/saros-road-blocks.pw.toml"
hash = "2aaeff09f7370df80ce2ee995fb90c49ab28d25b22fa02f3c752c377f482a280"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/saros-road-signs.pw.toml"
hash = "1848deccb87bc4308cca234199d4b5b4a6cc94935798171ffaaf4444b870a6f2"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8fed4a82792ca37ed74e3c2d283fca5de988c126ccee185d382909112b537c30"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "73417e6c30597aff70c1f08d76f12b4d6dbb8b873d82ba913982655c693a0d02"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/shetiphiancore.pw.toml"
hash = "c61ffea5a72780ecafad2c946b7e35f6ebe8d60c457a14e068f188c7584eb98a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "34a01bba9e329b13a4e7dd8717c1a6ca301b5bcb0bb5a98f0f6797ac02bafdc6"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "1b7bd2a4f6b288357fcf355162c9fdb140d02642ae64011ce5ef88aea3de955c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "1d5e68c5c723502d8593f654dc4be9332cdfdd0c4c6607c1c59832ddb24f96b7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "fb26aa161b7ac4028b622a9959e6d83539d2de6e2d530307be63b45907148b4b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "95d6afd00a9ea748d862058c96da20402652e533c5267df8d3b9f6c1b205d14e"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/ultimate-car-mod.pw.toml"
hash = "782da3ef7aff82736b11e6461259cae300dbbd6fdaf8f28d16a61859ce625144"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/vinurl.pw.toml"
hash = "07d9fe08297adc3f18d415c76b01f1a5c5819f0d3b81cb6ce8c036d1fd42bf0c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/vminus.pw.toml"
hash = "b48ebf6ae01dc386ec04f2830eb5382693d51f9679fff185c31a27d1b4fda838"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/wojanek!.pw.toml"
hash = "b14648aa49ecc91cb8024924ad79211b91233a3f50cafdbd5681c6716f4259e0"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "15a0f98dacca9c151c525b76ca8518f5a92939e9db957d8b0f5fe7bcf190dbec"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "52772f6e2e9f135b13d05701ad513da035e147409b7834fe12eccf738f7421b3"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "be542f5448b6622b8c863d9512bfb47266230e8d40f8cc9e66758a11ef1ca158"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "13e53be21b9e9f37ddea278980c765f1ed457c773bfe09447cbcc7203e99cfdf"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "a6bdbe7482e60c21528076a4146a81e3342b1611bad669cbbbc4efb32740b249"
hash-format = "sha256"
metafile = true
