hash-format = "sha256"

[[files]]
file = "mods/accessories-cc-layer.pw.toml"
hash = "0a73197637c1cc6a7858cc93cc720b8a391ab4e8ca56bce623552f88db82b093"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "f1b85d87dffa14793e8a954d6d629e7a17a17e0060ed25db2a1b6a3b58d954c3"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "d8ab469fa67e5ffe3487eaa644d3dcbb15865e8b0ee7f1118725e20b11e871fc"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b88cecaa12e03fe91c82283c495c7d4c2bfcb84be51995c4a433c0250891a011"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "302c338b3662fdee1078bedd9df58db70d1ddbec10c98580075071aeed2947cb"
metafile = true

[[files]]
file = "mods/backported-wolves.pw.toml"
hash = "080f6e18872006872847d0553bf9ec499565e84e48872cb70e93683740fe509d"
metafile = true

[[files]]
file = "mods/bartering-station.pw.toml"
hash = "443adf4d63cedf929e010eb39d58b5362dbb513ec0b014391505426d4ed8f1b7"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "06477ff0796f0bfb7aa20396b85bc82b83a2a80be3dac97403ceaf60e41e6d1e"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "785cd5b01e99393cae82c48abd98425dcfbac245f50aba14671657106d972d5c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a465a9eaff568ffa0e18a8516c1dbb8d9a98b865bd171577300e01c261e4604a"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "aa691b0c5ac0848ac32f86ae7e451bb8223f27920ba4475419e359eeb2ca3b6c"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "7221028772dcefdf6e61c9994688eaeb4fe3efbf05a50df5db67994a6fc6dee1"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "0064b3a694cf4a6cf1e2ba78fdee0e7738766cf138476a712eefd8415c5c2b53"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "500c192be3f4989e1a0de618d2d3cb1075aa644bc5a114cf4c747bb1559370b2"
metafile = true

[[files]]
file = "mods/create-additional-logistics.pw.toml"
hash = "e6df0e058af6d2b072d5b4c19bdaf3cc6d5aa8ec9ddff352e1624ffc5eb6ba7f"
metafile = true

[[files]]
file = "mods/create-cafe.pw.toml"
hash = "aa47d4ee446904ab11d7a7126c0b74a1d069062e532d00d7a8cfa6d9c36d6641"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "75d165cf0befe2d797f46d00c56ab2644d658468316b526328c31ae3d86feabf"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "63a59d33dfe288ceeebf582e3daa947dac6efd33a984424ed0557cfc4b84dde7"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "4064acab8132585a4c21a3fef6bfb9bb598d4ae9b3a6c4adc4d1e90dd361eaf6"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "f2603982fc8e2c6a46be6fdc160f2c3b071c2a46f371bac4d8f6143cf950518c"
metafile = true

[[files]]
file = "mods/create-high-pressure.pw.toml"
hash = "e0120922b4a7bcb528b4119543c4df2eea8669662bdb70c2a4563228bd7c1f5a"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "13bba79a5a22042f5fdb332e357082865b669654979a07a2a6e751cf386d0b49"
metafile = true

[[files]]
file = "mods/create-numismatics-crafting.pw.toml"
hash = "b2a66905fddc70444e7c39318a3e4b078576f5e292e0e9deb5bf54c10d23927e"
metafile = true

[[files]]
file = "mods/create-security-program.pw.toml"
hash = "24e0b22061865819cd627bf1c23fdebc383c341c04138b40602b4e8199791483"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "882dd50766e02c0fd858eca69001399e9cce073035f10a6832ed3c4385648b32"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "d5a33865dd2f35d8ad6b84e454f2cf55acd45652418c0fdf97da8cff3f22ead1"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "480dc5e43b2909839f1d514960f5fe6873b7914623514fc9307d73d54f1a2ef9"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "ac3fc93c73a20f8bfa8adb077ba603d549e5e1a62c32916abc48b433203ce47a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "98ca12055c7b4e0b4b7ba614499d82164420a8ae2db35accc51c0e9ad9947af5"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "7a59f84f4911b54a694ed1f922334b6ce529d088ecec9efbd9dfbcdfaa73c19a"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "237801012f8624d6c422e5fe404e3674fab3dac97043fd261e33ac158741385a"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "3cdf625ca8105dcc8407cdd63067575319f455ded91beaacbd6ed9fd580df657"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "3ff2fa5fd8eacff18674e2b18850afdd5648c443dcd847ed6ca1dddfea4e0a60"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "094411afe1838cc0c0ee6c2dc29bcdc825fde8a365249ef46c0bc3a13a45c87c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "8449cf1fd3806cfeb9f8b8c3bbe0239f62dc0cd4209f4656dc990a9ccd22e5ad"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "702e47a5e68e28c0cd503b0e23951a397085a9c09cfaaf17828b6b557d8b4727"
metafile = true

[[files]]
file = "mods/farmers-delight-compat.pw.toml"
hash = "b6f9ed5617397916703b94bd70923a10f9bf9be2dd9ad9fd9d3c5aee8b68d46a"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "159c6ff75cd71e216404cf2ec3270666bf0f0318ecaf388b6b498aa6adf64672"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "a60c7ddf9a689e8a5a07768f24905240c10eb82c93565b9e7df563b47a0171c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "faa8443fb4238730fc6314e0d8d0722ed5b50b76c3cd5b08063184c2af7b14fe"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "09e9beca364014577c685703c7e49c095ffb9527ce06c65842156bee301f7efc"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "fb7c5c884f1286061f6bd8512305619e39b717f271c461e575433419006aaabc"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "18bab08379e93476e692f30d8d862e802d3f5fe5962383538f499cd6eeb75b17"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "81c3e392c70e85098348b89426962047131202b8c75390699c7bf7a392452755"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "9ea84621321352b22b26115ac633a61e5685353da2148080ea685f78add670e8"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "e45d31ebd2b2b8cc1139934ff4e881f5a76f589e97558c93fc0704a86102cd00"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8fe1ad7294240eb1fba18401054212f151713f9d0cac00a43115223684772194"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "486fb7fc2dffb7f5f9892bce6253703f5d8ed2df964c0ace058ece2c9680af5d"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "e3f65e290d2c9b0fe6602e7b712433a0102ce7e2b33c12e2915aff173d5d99aa"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "f71c41434fd45053c6878069875611f3bed05c69512efe55546d75df548df2a0"
metafile = true

[[files]]
file = "mods/mcef.pw.toml"
hash = "20dda2a6dfc1cfc2a191515e88f8e953b7a8f182f1a3732d7ef70a21f23d9ff1"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "47c35e9b29937b5566e8988cfbce1834c4edd0316edd38f6e7ff7a8d1dfc1854"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "ca0607102926db11e0c47b5039fd7c4d9a0adb92f41476c0da724c429438d7f6"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "ea314c485c51d50a83a08baf403f1499f5f8af72405029b2e0f1a20717e0e4fb"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "d78518ca3133a2fbb357d7371521d73b71ea5e82b63c45babc7b7d2c4fc14df9"
metafile = true

[[files]]
file = "mods/multibeds.pw.toml"
hash = "bbdc1a340ce679842124e4d78e7c351fc50311a33650774ac8e9f07de33f51c3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "8306c030be24c3df8edc4635307a34bc193267881f7c794000cf2fe7d6860d48"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "cb88d2d0669450c6b85af0d12d2471496c0262bf1339b8b26f428ba1e5790bae"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "0fb401d1aacd9572cc68d3c0120bc4a116c987811287128e7414819fcae766e1"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "1b92e894a78ee0c297f87c305e987232110c87b19b5567648ade5527dcd3c37b"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "7b87da376428165274ef1c39984111bb30e5b2e7ae557e023d810d1335e3eea6"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "eb27639089888a9c9bfa99bbe93a1e0a02175bc276fa62bab1ae8c613201f9b1"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "f11dd16ab22c35236fd8b9c549486f142d0794715dac7027dc691302d0146391"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "de2cbee4d51df6e2154ff53eb379cb3b3948bc0fc1e6b81688e79a4a7bbae8f4"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "b14c9b27a27fa0462949fbc13004f3b714f1bd6cd31a0560bb89404e128f6789"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "47c0b74899ea8ecbc6c37a4605a68687eae6e5c887997a86b5031a1c1bdccb7c"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "64073d351900fd72cb6f2b81d2012108e2159153f67a949a0e831c0d23d3607e"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "8f6c454f42cdc38e5e763cd50a4e514939007807244e75b627a3d9354c6ae9fc"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "6650ad633fcf6230cb490519a0e14cfb2a5e6fe9ffc89b041daf3928f47a0fca"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "02ba1f2ddfca07dab4a7f3c143f5382dd2db5a6f250e9d9f22cef5d304c9af0f"
metafile = true

[[files]]
file = "mods/saros-road-blocks.pw.toml"
hash = "1a51adb4105d10e27316ae5be752ffa0b273c49c60c1881a9de90511e7d5cec0"
metafile = true

[[files]]
file = "mods/saros-road-signs.pw.toml"
hash = "c8df6cf49f54aa9c0134b47dfa98e195a96a7158884b7b11516ccb2e6c50e873"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "d492084a09cb77a8bc9b7f9575c2e948a488d9bf9f5265df998b8551e879847e"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "73417e6c30597aff70c1f08d76f12b4d6dbb8b873d82ba913982655c693a0d02"
metafile = true

[[files]]
file = "mods/shetiphiancore.pw.toml"
hash = "a755a204d6fa3195abee149c79d098cfeab353be3017123842d88da944fb63c7"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "ec350deff79de6c3d91f7846ab5af5f6e3ddf9e3faf351035d72e7c0e84b5a87"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "b1625ea52f9d59df3d2698fbfae3b2fb69e0cc4f7b848767e9c7445e64f4cd3f"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "18ffe40e4be5429644099d25627d5c745fde101c7a739173d35a38d81228bc80"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "fb26aa161b7ac4028b622a9959e6d83539d2de6e2d530307be63b45907148b4b"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "ff0e878ab51b6f39c2975a621b852811fca5fa0c80244de4e7ca406c3144a776"
metafile = true

[[files]]
file = "mods/ultimate-car-mod.pw.toml"
hash = "782da3ef7aff82736b11e6461259cae300dbbd6fdaf8f28d16a61859ce625144"
metafile = true

[[files]]
file = "mods/vinurl.pw.toml"
hash = "07d9fe08297adc3f18d415c76b01f1a5c5819f0d3b81cb6ce8c036d1fd42bf0c"
metafile = true

[[files]]
file = "mods/vminus.pw.toml"
hash = "b48ebf6ae01dc386ec04f2830eb5382693d51f9679fff185c31a27d1b4fda838"
metafile = true

[[files]]
file = "mods/webdisplays.pw.toml"
hash = "0c050be514ffa1f89cc0242b3b5ede5422059be7006dc1f9e0ddbd6f3c7aca84"
metafile = true

[[files]]
file = "mods/wojanek!.pw.toml"
hash = "b14648aa49ecc91cb8024924ad79211b91233a3f50cafdbd5681c6716f4259e0"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "15a0f98dacca9c151c525b76ca8518f5a92939e9db957d8b0f5fe7bcf190dbec"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "52772f6e2e9f135b13d05701ad513da035e147409b7834fe12eccf738f7421b3"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "aa051e4111e04190083852f438223ac97d8a597ecf5c747aff649b35b776ef0a"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "13e53be21b9e9f37ddea278980c765f1ed457c773bfe09447cbcc7203e99cfdf"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "ce5c5b9179e868a98912100b8f9cd18962d43668ab27673b8b2b0af75466d256"
metafile = true
