hash-format = "sha512"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "442adae9b52bfc500748d5aa11ca055c7008fb5c96a40634130133788004ffdb"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "5a53be204efcb61ed865b934d60f0ed29fa74d02ebecb1276f668d6baa57e40b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "8561092fbc294383bca05ac337ebb5f598b553d2d78de8acd474795e1b84b3ac"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5fddc01a95ce404ec31b8d7140231ad5c0edb39088b1e097586f8da619327418"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/autoreconnect.pw.toml"
hash = "c6f16688cf57d7bf77e10d746cb4ee9d07b4d5b6c68a08ff74680f5685e30eac"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/backported-wolves.pw.toml"
hash = "c57aecb17789d99fd6b405b8c0a692858e54ee763436bcdc1e0c9b0ac3fbf156"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/bartering-station.pw.toml"
hash = "af627b2b495c426167b66e07bae9c9c8eb80ab43155d02b5244232bef6275d76"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "e8c215f7d8aedb6e81efdf2ca61b1d964c52c367ff5a7682ae06f00fc08ea6f7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "798bd88e2c120d2d69d247802d9b577c8527ffc30052f6c6d9258932c3f420b1"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "cd276ac647cab1a63ff4dac9a8480b8a299470953e93d51ee81f910e60d8a998"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "a9aa79d6073e34fcc96ef19d63382a9622dc8b46960da1e02de1adf131223e7d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "4d5ba0ec7ea7abf0ef76f3f08853bd7c886eec95b1795cbeacaba8bc608e2913"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "dbe49e21c3f4d8fc985b84b49c6be57e0ee929331527d3e25a5dd17970d10223"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "ed65d4275410445b909709563ba487751c97ffc35c9f79ba40098d796dd2c5dc"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-additional-logistics.pw.toml"
hash = "65b606fe6a499acf0ebe2cce6b923d9698d9d61cea998f34eafab2c18198c7bf"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "fabe3f3b9ca8fc741a0e01890b7518da51cb3dd3a27e4d95e2953dbc58184582"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "ccd4dc50146ccc34745839800343705b2e3cba44b0550604620630a06c240b5b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "fd4092979a2f31042442d6bee609a801aa1979b2a3140a9fda98a2e3c42505cc"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "d2dc29aa6f3a1870aa22fef24430fc6fb42c088d93da815ddf5d71d95ccb5d7a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "88aca7f5341cba8dcb829fc5dab2c34a90a629fde5e533a66fd9ee68ad463d02"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-high-pressure.pw.toml"
hash = "c9a3ee33821d285583e96ff2a665884e3643ebb57f0db9f2310ae6f3e902575f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "3f29e36d9b68b99e1e88e8782fa5e7f65d34716a39cb8bab8130e1b5b7e47fdd"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create-security-program.pw.toml"
hash = "0cfd2d7b11f2e0fcc872b5958927099ae93834e1ea24f3114ed105715dfd69fb"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "f9eb00688a81ef928365fa3b763c2d0e801057ededba16031d9ddf2b827513e7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "f167f466fdd669bc6946eb9605f86972103ee17905a0689d5f7d10a18685b02e"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "e1769039ce35864766d724e325f591594a5a4b99bcf23d82f6067bdd8d26131d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "451abb8642829da6e6d27efe599cd84effe14b55aeb8f92520719bc987c2778b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/devices-mod.pw.toml"
hash = "7d62bb1a849b5a027bff698a10ae8f5d319b5e3b6f7da5c14c64b3af47ea43c8"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "152572d2545d92ea1d634015e584e883a5813ed19f8d20c7df8622848493ee2d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "fca87ad8b9b6f05f991a745f8e54069dd7635863fd5b3894150ff744c51917e3"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "c2dacdb110088c3895d533173c4d61d376ad33acef15fe4e67041f4df33f7994"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "fc78c27c31e86bb6ea3d061bfdc0a5f9750d557f37233833848dc0a58b6888d8"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "2a5ec036147e0c0ac36f551c0f5e357afff8de395803b0dd5b6a04343e7ba1af"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "25d3f272639cef595de126a2c51faff793dc03bcde63ef060e1277c315583ce7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c61547fcb79cbc520c73374a01430c25af6ce2de258f019bd2c617b2d9bd71c7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/eyemod-phone.pw.toml"
hash = "af87205351b0162802eb9bf699ceedf7a67e0c376810a9423ebe26c286b8cd2a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "c998d6f5b893e1f15e4f9610e9340d6c2f3fce5c8adf5902fd098e74e099d773"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/farmers-delight-compat.pw.toml"
hash = "4da5493086bf5e03b5d49bd9da054e227069b885870f526705a9003a740774a4"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "b93e58a5a61339d8829224cba12ef208b74c48355f87647b314421e6b0325632"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "acdb589e9191d1d26da2468ba1eaeac85ea96d3027129e56578426c5adbc6793"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ef60a6cd0d0e4311ed1ae95b79616b5da4d618290a1594a76c874ff1e5bcd9ba"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "26aa198d31b72a9c98081aa11f9c9b42a4d5934fb8956e753b6d366d22166c58"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "68fe263f1a5331f9c12b79a99ef1047c91b5451e69a244cccb2d02f1a6c16827"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "a56562d4e3ee2511b5696fb9fa9b974558b13de98fc2db8263bb14c7e5219013"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "eb35aacfda8731f4c83b280f130cd7f7d1b2e1870acb63f744582fa617704b14"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "602b107704d7a826b0fb6781aca204eb4dd902a0fac246bb8048ba2a1543f9d7"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d2d981a21b9f75cfb5804476f2a5b6cdfd6458b423b3a11ea661124146a8430c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "79c990b977cff2edcd25258c91a04feae5ce3cbc619f2b9e5af0861f83024791"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b0441c2b5bb6ff680d97eac28d95847f0d4dbee34d1d42d897997b500acd44ca"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "7f1d1b0b3e788df1e417a127fd62258197c2c9f91dfb9c1b4f63248f47c9b03c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "2b7193f279cad8d09f23dfe0e3ae97609624f2f85434b3d34c9987dcf3e1735d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "12a34afe1b9089e25275428fe9dd1efed9724effa039350a26e5d33e88954f13"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d561d4a11e70aaf7b7881e4d45af6ea8a9a49303dcef26d6a00c7778d8876358"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c3fe09de76654cbd7012ab476423de1eb1e3ae80cc2a3aec7ff547560e1b56c9"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/multibeds.pw.toml"
hash = "9b706cabc28929e7634ef08a5cdf67e2af6974515bb5d82aa42f37fe5d268143"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "bbd3c79a8e40afc8f6dcc44ac73f61702f84250b04e9c2a1f7e5c4ae75fb0157"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "d79cc9f98ea57ba7040181547f299f07114843e8bc12d2a3aa1f74962ee91b15"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "7ae487dfc408a96790c37785b5cafa5bcc77a2f520dd5499ae3598138eab6a32"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "8490ab74a0ccb5d368332355b8fac2595a746e4578f1b26821d27c652caf5fd1"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "6aa6e62ddf44e5f07cd9fcf356ef9822a71d42eadca902011d028ed27b639a07"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "94901c5541b04ab34cdb7a5a26564791d94c819ae37ceb094e6e202424b83b47"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "e76063890f364d2cbbbbf58ed46883d4dadddb7abaf0b83a6f75c3640c789ae0"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "9e9e9848f7cfee98b0bb46833d95f38cd0dbad11122b3f332b206d1164ae9e80"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "ebd06dd6f14875cc9b6ed1abd17f805021e1ab64917154718703f096d5559b3b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "97930ff0259217cd6db1592796c806508123539157307b9efbfde398a4f4b91d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/realms-button-remover.pw.toml"
hash = "bbfe4c579d6adf0d6c4f87c063bcfa186c217b131953e528c4382bf62c60fda4"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "3f45527ded48855b6cd7feaa5b6ce3e778899c68f7710d0bc1c880ed4ce9f7d0"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "bac29b241055fcea8c0c185101e53aa4d2b4b49f4ad6f1bdc87b19219d0c5a7c"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "dbef894bebfab44ae88b935c62501dbeae98cd62e006b4cdc0ca32c35aeaa9a5"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "f9bf3fe464ab266bd2eb8eec780c3c1c7cc0c33b3c34a5d5d5681d6887d8c28d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/saros-road-blocks.pw.toml"
hash = "7e2dce9fd0e13bc8a223cb34afa3b05b194c48fc778ad6e04b4dd31516955f8d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/saros-road-signs.pw.toml"
hash = "50875b5850d7b7168af8726d3b5362b6e2bacf1a5112b2294a369b7ff997ced8"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "db96a789a2b561c2ed9be3508c324f34fd212ff656bd1f099482596f350f6eef"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "4a4a5c1cb10f4df900b3963dd9601dbc8c7bb31b03e49109f61e21a4f5df9883"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/shetiphiancore.pw.toml"
hash = "8748cbc06c6db9faa764d5ea63ac2c6d2a785cd9506bc7d68510f9f5b4f61bc9"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "812e982255eb5b8adbb8665e8b9da898d2b5737805ce0207ef5012e7aeca3b8f"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "7d8ced17c01898804a9593a59ac78ac32d72b74198fde3fd65d8a0f02afbb81a"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "01e1c8b8e36ae93c36a64e26f0201e4564a7b3ec68d2bce80546d031f032f9b4"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "de154b02a11f6d077caf56e6ca8716442787b05d6fc76fdf95ce1d5c0848a710"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "9dfea69abcb995302a38aa037b852b6fc1e07ff65169b71d3098151cacaba77d"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/ultimate-car-mod.pw.toml"
hash = "b04d24dd12a7e944bc282537bec12a00e2a4539fe720ae2386a96163666a5a42"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/vinurl.pw.toml"
hash = "6bc7369270b79cc8138b6caed6241beeb6bac18c2b10669627d3db2f8fcd1766"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/vminus.pw.toml"
hash = "898203725dda804453ad92ca0e072fc86431d66aced05e3686caceb285f5495b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/wojanek!.pw.toml"
hash = "4ab59812b9d08626989422dc6130404e866968bbad22689da85152806a2400cb"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "aca59c694729644466047813a7bb26f1c16fa3968788c694f77fa0436199e907"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "25219ada37bab9dec8957abc4cd23f626f1b206ac707e891c95953a341c63755"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "7c34d73ebc68038f6820aa89a4a315087870f7c3c68bdbca5db556578ffe855b"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "f90cb6aaf8d238027ac89adbd273bb45b8f715db0e43b7d466080ae03613ebd8"
hash-format = "sha256"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "f43db9b7b6e369fb3592630dbdeb94b905f85f09b608d94ec2c31856376ee752"
hash-format = "sha256"
metafile = true
