hash-format = "sha256"

[[files]]
file = "mods/accessories-cc-layer.pw.toml"
hash = "ec3adaa1c1b1b32cfa7abf8ec7a21ee4df11843d3543d07879652733766aa24f"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "4ee1822943b01bf42108cc4baf2a62baa8a8c26b0332639eb1f77951e232076b"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "2feabd901652b106f780b3313b6f989bb470636d4a9130f581442117ab6f39bc"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "d1b1d452f6a702d407078ca19930f4d824cbaffc680999e0f5696f90375b8f81"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6caa80913963de9217eef2c6a573374823000d085b9a377720ae65472cc01a43"
metafile = true

[[files]]
file = "mods/backported-wolves.pw.toml"
hash = "20a73b10d5d1fb46597f783a882b19e49758a01dd890a3a235ff6e36c651a324"
metafile = true

[[files]]
file = "mods/bartering-station.pw.toml"
hash = "8b85bef7afc2385ff0beb48cfa20c0bbddd5395e786aa33b501b00b32f933f70"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "95cdc4424d430148cb134ddb8f0a753e25cb75eaf39da135f9cc68817ef70419"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6deb8a0d0e44996e3d8d6152274265f4cfc460c8e40f661378c721fb22de1565"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7616f567a0ce0616a5310053d45faa4679ffd4ffcd0846589464adc059b5623f"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "2c45408c8feb9ed7f7f2b9bca1521069badbaa1f41c40750a01e75910f39f3b1"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "637976b01efdb9da4c6b47bbfa950c746d68976255bd974f227260eb8f9ff3be"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "1f5242c5c6f5deebecade66f240f5da46ac1b49911d2de02f1989c67a589f481"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "2db5f5c79a1a522006cb582c93cdef2a0754b50ecb66c49ddcbd35c408b9dd10"
metafile = true

[[files]]
file = "mods/create-additional-logistics.pw.toml"
hash = "eb9fc90117895ec42f448d7b43a2f060742ab6a0ae5b5bf2ad88e44b2d225468"
metafile = true

[[files]]
file = "mods/create-cafe.pw.toml"
hash = "d6cfd6bc1d0a877d52bc222a43c96a09b0316fe79a9abae7d8a841bdf19853a5"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "4b64ce523c99d9a09a179ef286216d596a20b547b342a69cae9aa70f0cd64b25"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "3795f7c1b4548edaf6b965decc0458101f2fa66690d2336c6abe8dba3a9b6856"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "7902c152cbd0f99cb0a0d73bfca38a30fa4cf86518c56f3d16cbc0a2e0c6f1cf"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "0f22d887ccd0d6a1f261bf7b6176c75e0340071ef69b7ef71bfe7891a324a96c"
metafile = true

[[files]]
file = "mods/create-high-pressure.pw.toml"
hash = "ae513c23f4e705b159b56c93fcbfab7d0918d2fdc5cd02e8a76eb515e66a08a8"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "e460b3cff3bebcffd18ed74c6f17b404b2c443ea437fc3d8e5b27f99de7a47f5"
metafile = true

[[files]]
file = "mods/create-numismatics-crafting.pw.toml"
hash = "77dabd5b69086c66fec9ec87596ba8cce7552b76f59aa0db476cc367976bcba3"
metafile = true

[[files]]
file = "mods/create-security-program.pw.toml"
hash = "36d39f076456b406ba6e5fd4e23eeee4e65ae1873f677b790db388fb75a84fb8"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "98425e1896d4aa51eb437f0ce892373d373684ca5b054ee788d60e69e97e4dbc"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8f194d82fd7724da1f59daecccf1de06c7ed96ba1b33ba3a0276d0826e319668"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a0783f37beae8e378bddc0eef69f60096b7a65dbf084bd355bb64ecf3f821906"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "c1b2d26f67cc271560ed672b13e613da0ae8de3be9f881486ba13ba6f2011e4f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "cff0af55e864132049ed883e937dc9f139cde7a0fad1a16b897299a6fbd714e2"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "532b0f153fa80d2fc95598f9efb718eeabb15ab9d0b96400a620eaa1fe4f9df5"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "c64235fbb1df0e81ab712f8852b7c783ebf3c77663c620a8ac76b47174d138a2"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "4bc90d0ffe8d1ac3028d1376bf773fd8e7f1e3a8622f20c62f6076626e26c692"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "f62b880b838a3e3e6eb3c9891064c966fe7eb4c519748d4d62680d63b10a8ec8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "dd746afebd7d5a7d0f7a30fa58dee28cd3dbc5ea8c4dfc07cc10298ff46f27ae"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "140fe0ab02edd0af48739b8c77fac6b6546d6623a06afadb53ba1bb0c7bc7090"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d69e9b4b39971f9372750f1e09593aa3ec889ade91dafa094e91ef408ad6cbdf"
metafile = true

[[files]]
file = "mods/farmers-delight-compat.pw.toml"
hash = "c54549782ce0d88a55a621f20d1ce4b069c583b3f8f5b343bea84c1927c01fe4"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "168400b0d4f3ce42530b8ecdc861c59c9bbf2790e418d3e1de719c4639c3b5fd"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "27f38d3e948e7fca1d22a6713b6b0779e494b95e778967bdf5ed14388c644023"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "fb50c8bbacdaa8c1a5bf4a866b8266fffc11d9097a5f00a8da37c01719a1cbd1"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "c9640720d7ef5f5eeca2d7ca535849ad62fe6f75276f44dd1a234f452b72ec20"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "43be94c7caa9f7d6ff4be414f82100e4c13a80775da7049411bd8beaabb68d29"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "7a390b9896cf22b775a5b30500e6c40df292cd48e30bd1e96335371ae5d01374"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "072654309578117bb61507b8aeff7a548160eabb7a9c7552b1ff511f364b568f"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "3c41c9bb587ad3ca707bb5d8fa17e12087c9a028c49592a9066576e2662c0a10"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "4d5a06da43112825f181f83648c5411270fe1122b239eeb8df4e38cce8983802"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "39ee1c700853d5d32e90485bfdb68d6b6a6f7150f307cde751d915c9d72bf7fc"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "a8a7974429a33b887508020bafbded30f7d87287b3dafa74d414fb58c458a36d"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "84c514d84c668d482231a17e73f694720777c5128ef1a9b5a49de630768ea94d"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "321ad67d68c39a6667c0180dd9a9f9a27351d3fa13ba6450a0eb2ca347810894"
metafile = true

[[files]]
file = "mods/mcef.pw.toml"
hash = "57f98d93aa30b75ead0c0dafb31a790ab796407d20489b75d9ec472cee1de8aa"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "9237918694dbd4ec1fe5a41f7b2357acb9330877abb86cc77d99a47fb3b7e9c6"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "af252ae159f7c058a892626c778889ad43d2442a571c9c34a65e5bf3ac9707fa"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "055f61ffbdc8cebcc7fc3de9c2b5d06379c0f62dc8fd0af2124ccbba4de87971"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "181722af88d64130ca2790c7dfcf350e2ce2b033d9e1825cc4609db756ea42b3"
metafile = true

[[files]]
file = "mods/multibeds.pw.toml"
hash = "7ca9e7e7e97b18fd20f343b1b553442d3e592df3d88967aec41ca839097aea16"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "62af8092bc6cb23f21d2a10ca6baea212f08c5d6a169c0b188a84bf20b60bb46"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "1e52b2cbc9d6d05afcb23ec294dd897d18de6ef15df757d78a6c540114d04624"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "4335717a05b3266b4015d239b35c266a0af953c02f298bf0878776764e4d2862"
metafile = true

[[files]]
file = "mods/numismatics.pw.toml"
hash = "3c46fcdafd0243a51d46a1546a67bb60c66819240d619a25e28431a2c48320e7"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "6c2d8742a2cf03c6370f929c3a08812da6aaf9baa0bcbc9774fc28ab8779f42e"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "444590121c8995227af4866735f0f8bf83f634012c117e318b0d75df6a26bde2"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "c570281f185ccb32edc4af470e26c649d13707c513396c4a4880f1ac0e261dc7"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "b6f97e97cb0951e928360a41771ab6a5472871792989497760d02a1e4d1588a7"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "e3ecb9435c300f11d7d567ff1163d488edc9323581ecba65282ce58b366bbcc1"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "71d7615e4bcb0abd40e6ceb229f58a83778a02b43fc9f0616cf3404ba4d65695"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "f39a70bd1c20e3ebf0337cf74e5d338ff8841f85b50d129ae7cbb7100c8176d5"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "41567213901b7e8bc7312097186d7e4a6acc0e45c98a69d8a74411d59696ba68"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "1ffb8a57e26b2c25257a867b678eb985641f6a7d713caa29ab0e05eb83f8415f"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "a6a5abab929f819c08cf84b77f9d807a50d552a21ff902e27fc6a3292c98a993"
metafile = true

[[files]]
file = "mods/saros-road-blocks.pw.toml"
hash = "eea2bc86368b3ca8be6ea4395b49c5a1feec4721c5f4e706c6d56a332e9ab50a"
metafile = true

[[files]]
file = "mods/saros-road-signs.pw.toml"
hash = "ac25f0b1b77985da9b24aa7fec2aefdab335382514f3a02ab49910c6a85500d6"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "7c942306b89b91c8f540fd57d9d96dadfeb3a8df5babd7f727d34c0223da371d"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
hash = "237fdfc57414be995d4809998b4e4333528e930dcb6a098c450a65a3c5dfe0f5"
metafile = true

[[files]]
file = "mods/shetiphiancore.pw.toml"
hash = "0967377a7cd75a6c9cebb5dc22f8a758ee2674e969b3f223c60d7f27e78128ba"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "99cf1555e90aa86d44f81384e2b8fa99947f3c1cb8a83581976f4cf059a989fc"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "69db26c7ab8445969a535b73e3c7ced6e42dd44a14cb35398bcb6e9bac67ccea"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "85a76cabbe2dc9b180b31a91a4a5ee07008f9c0ec30f0be818eae70dfba80576"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "bd231d37183119e67b5d93923c5825bfb211dfc8685d712c20714f7cca212941"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "57f317e66fa5c0d9957348c8139a329861b8bfcfa4c9a285a98502bfd00e1ffc"
metafile = true

[[files]]
file = "mods/ultimate-car-mod.pw.toml"
hash = "de3ef1c5d0c41f00c629e0fb144ea781591d7b3a28a12896b714634d3b9c2313"
metafile = true

[[files]]
file = "mods/vinurl.pw.toml"
hash = "32a58ed2559c9e1f5d933fd88aebb3e48f580226280918d13cb344bd0b7a872d"
metafile = true

[[files]]
file = "mods/vminus.pw.toml"
hash = "4c97b0393c29f376b1974d0f515ab2fd958de311a14c5e7f229181f4eb5634f9"
metafile = true

[[files]]
file = "mods/webdisplays.pw.toml"
hash = "ba9eea75dda5d0bce8d7faf83ec0dd2aa3c99fe3ed4366a8bff1c0a684ef1594"
metafile = true

[[files]]
file = "mods/wojanek!.pw.toml"
hash = "86edf3292d744a15fa73d15b78f04292429725e1823df73703661f3162ccf5c4"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "2faab02b576f8bba9ff88fc3f922217ece69a9f451d70be3548137d4b796d5b7"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "37a85c8b963d143c2fd0fe0c5f456258fab0e4c8e92c8c06c471a3e831751c26"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "98d6a015d25ee0ac5636913f8c30903afe350040da767d89563d732590d6e963"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "60818915bc95445d83307f2f564ded2c28ccfed5b3953c532bff435949dd74d2"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "3239d015cfc4069812fac1be247cd1677d3487e79852c5205163d9cdcce56123"
metafile = true
