name = "Paczka"
author = "ewvbm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcbfea6bd6652507fa6dcabf0d9a0f612e69a0c7099f02e49aa9437855a50a49"

[versions]
fabric = "0.0.0"
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
