name = "Paczka"
author = "ewvbm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8557e9e56c62a00071f415ab90c9c1ed69132259d9fe73b01696f4634c8f17b"

[versions]
fabric = "0.0.0"
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
