name = "Paczka"
author = "ewvbm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c8b31db1ac03d2dbddc89321bb983a3c3590b7e46c5c7940ffcd9699f014a97"

[versions]
fabric = "0.0.0"
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
