name = "Paczka"
author = "ewvbm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6315a49d90aff1afcb5138a166c132e2db100ba944b73b71430b77ceb588a1e"

[versions]
fabric = "0.0.0"
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
